### ISSUE TITLE
[Add-on Request] Field that hides/shows other fields

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/addons#11]
Back in 2016 @OwenMelbz created https://github.com/Laravel-Backpack/CRUD/pull/165 . Basically what it does it that it allows developers to have radio buttons, where the selection determines what _other_ fields are visible/hidden. The field might even work well Backpack 4.0 (though I don't think it works in 4.1 not in `repeatable` or `InlineCreate`, I assume).

Personally I don't see this as becoming part of the Backpack core, since there are A LOT of ways you'd want to hide/show stuff (ex: from a radio like this does, from a checkbox, from a dropdown, from multiple dropdowns, etc) and I don't think it makes sense for us to develop and maintain all possibilities for this.

But since we already have a working solution for this (at least in the 80% use case), I'd love to have it as an add-on, if someone can commit to creating and maintaining it. @OwenMelbz let us know if you want to create the add-on yourself ([tutorial here](https://backpackforlaravel.com/docs/4.1/add-ons-tutorial) - not that you'd need one). If not maybe someone else would like to pick up the task and credit you for it too. 

As far as I now, to the existing code you'd need to:
- [ ] follow [Step 14 in the Bp 4.1 Upgrade Guide](https://backpackforlaravel.com/docs/4.1/upgrade-guide#step-14)
- [ ] (maybe) make sure it works inside the `repeatable` field type
- [ ] (maybe) make sure it works inside the `InlineCreate` operation (in a modal)

If anybody stumbles upon this, and wants to do it, please let us know.

Cheers!

**Comment by OwenMelbz** [comment]
A blast from the past!

Anybody feel free to tackle this! I’ll try see if I have time during this corona lockdown, but don’t let that stop anybody else wanting to contribute :)

**Comment by LemarinelNet** [comment]
Was searching for a way to hide a field depending on the value of a checkbox, and found this issue (and crud#165...).
Would just have loved to see a "hide_if" property on any fields, which would ...hide the field on the return value of a closure ?? ex :
`
            [
                'name' => 'product_has_components',
                'type' => 'boolean',
                'label' => "Product has components"
            ],
            [
                'name' => 'compound',
                'label' => 'Product components:',
                'type' => 'text',
                'hide_when' => function ($entry){
                    return $entry->product_has_components;
                    // or any more complicated logic , with booleans or anything else !!
                },
            ],
`

Thinking as I'm writing, the complex part is that this closure will have to be evaluated when the checkbox value change, so on javascript code !!
Note sure that my comments has its place here ;)

**Comment by conschneider** [comment]
Hi there, 

Just wanted to say that I gave this a quick whirl with Backpack 4.1 and it works nicely for me. 
![T5c44gzimq](https://user-images.githubusercontent.com/271725/95914740-72ff5380-0da6-11eb-96a2-87b0b7c596a2.gif)

Only tested it for a very basic (and one) use case so far.
If I have some time left over after finishing this project I might just take a look at packaging this as an add on ^^. 

@OwenMelbz Thanks for this!

**Comment by tabacitu** [comment]
That sounds great @conschneider . If you do that, please let me know if there's anything unclear in [the packaging tutorial](https://backpackforlaravel.com/docs/4.1/add-ons-tutorial), I really want to make it as good a possible.

**Comment by iMokhles** [comment]
Here we go :)

https://github.com/Laravel-Backpack/CRUD/pull/3420

**Comment by soufiene-slimi** [comment]
Hi @iMokhles, thanks for this [pull](https://github.com/Laravel-Backpack/CRUD/pull/3420).

This really looks great, in many scenarios, you will definitely need this feature.
Just wondering if we can improve the functionality, maybe I want to show the price input if the user accepts the rules of posting a new product (a checkbox field) and choose to create a paid product, so this scenario makes me think and ask the following questions:
- Is having multiple parent fields values will be better? and if so, will it be difficult to achieve instead of the single-parent value condition? 
- Is there a scenario where I will need to do another check before showing the price field (maybe some calculation or some database query or a specific date)

And if I consider that those are easy to implement, I think that version 4.2 will be a perfect place to introduce this feature.
So what do you think @tabacitu ?

**Comment by iMokhles** [comment]
Hi @soufiene-slimi thanks for your reply but i prefere to post your reply to https://github.com/Laravel-Backpack/CRUD/pull/3420 to focuse the subject replies to it's related Pull Request, if you don't mind of course :)

**Comment by zachweix** [comment]
I've been using the toggle from https://github.com/Laravel-Backpack/CRUD/pull/165 for some projects, but I don't know if what I'm about to say fully makes sense. I have a toggle field that has 2 choices, yes and no. When yes is selected I then show the user more fields to fill out. However, one of those fields is also a toggle field that determines which fields need to be filled out. The problem is that when I switch the top toggle to no (and hide everything) and then switch it back to yes, everything is shown, even the fields that should have been hidden based on the second toggle choice. There should be a way of setting what should be hidden based on two parameters and only show it once both those are fixed

**Comment by iMokhles** [comment]
@zachweix check the code here
https://github.com/Laravel-Backpack/CRUD/pull/3420

**Comment by zachweix** [comment]
Thanks @iMokhles I'll have to take a look to see if that's what I need

**Comment by bedoz** [comment]
Follow, very interesting.

**Comment by tabacitu** [comment]
Guys... I'm finally committed to provide a solution for this in the Backpack core... and it's possible I've stumbled onto a solution that would work for _everybody_... Let me know what you think about the idea in https://github.com/Laravel-Backpack/CRUD/issues/4158 . Can't tell if it's incredibly good... or incredibly stupid 😅 

Thank you 🙏

**Comment by tabacitu** [comment]
Let's close this in favor of https://github.com/Laravel-Backpack/CRUD/pull/4312 - we should have this as a core feature, not an addon 🎉
