### ISSUE TITLE
International Telephone Field

### ISSUE THREAD

**Issue by MikeyBeLike** [Laravel-Backpack/addons#32]
I've just created this addon as I use it in a lot of my backpack projects:

All feedback welcome!

https://github.com/MikeyBeLike/intl-tel-input-backpack

**Comment by promatik** [comment]
Hi @MikeyBeLike!

Great job, I was curious about it and I tested 👌

Everything works great, I just wonder if you could add more costumization to the field, so I opened https://github.com/MikeyBeLike/intl-tel-input-backpack/issues/1.

Good job, thank you for sharing 🙌

**Comment by tabacitu** [comment]
God damn it! I forgot all about your package @MikeyBeLike , and tasked @jorgetwgroup to create a Phone field a few months ago 🤦‍♂️ Looks like we did some overlapping work here... 😔 In any case, I'm going to close this issue because we have https://backpackforlaravel.com/docs/5.x/crud-fields#phone-pro in PRO.

Apologies I didn't see this sooner 😔 You would have saved us quite a bit of work!
Cheers!
